Remove Consul service registration
openbao/openbao pull request #167
Opened 2024-03-02 14:55 UTC by cipherboy

This removes the non-BUSL Consul service registration; the only remaining service registration is thus Kubernetes.

2024-03-03 19:31 UTC, JanMa requested changes
@cipherboy please also remove the relevant documentation if we're going to drop the feature

2024-03-03 19:31 UTC, cipherboy commented
@JanMa ah yes, good reminder!

2024-03-04 07:43 UTC, JanMa approved these changes

2024-03-05 14:51 UTC, naphelps approved these changes

2024-03-05 14:52 UTC, merged