Update go mod ref
openbao/openbao pull request #2
Opened 2023-11-29 01:37 UTC by jbutlerdev

Update `hashicorp/vault` references to point to `lf-edge/openbao`

This will currently fail to build as the `github.com/lf-edge/openbao/vault/hcp_link/proto` needs to exist with the updated `go.mod` file before the `go.sum` file can be properly updated

2023-11-29 01:49 UTC, jbutlerdev commented
#1

2023-11-29 12:28 UTC, Scorpil commented
Hey @jbutlerdev, hcp-link is [still MPL 2.0](https://github.com/hashicorp/hcp-link/blob/main/LICENSE), couldn't we just use it directly?

2023-11-29 13:39 UTC, jbutlerdev commented
> Hey @jbutlerdev, hcp-link is [still MPL 2.0](https://github.com/hashicorp/hcp-link/blob/main/LICENSE), couldn't we just use it directly?

That's correct, however since the module is hosted within the `vault` repository and therefor also within the `openbao` repository I thought it made sense to point to our forked version. Do you think we should still be pointing to `vault` for this?

2023-11-29 14:18 UTC, Scorpil commented
Oh it's in the vault repo... Nevermind then, I assumed it's pointing to the separate repo, my bad. You're right, we should keep it as is.

2023-11-30 09:03 UTC, Scorpil commented
Alright, to test the branch I've added 

```
replace github.com/lf-edge/openbao/vault/hcp_link/proto => ./vault/hcp_link/proto
```

to go.mod, this allows me to progress yet build fails on a compile step with

```
# github.com/lf-edge/openbao/helper/testhelpers/teststorage
helper/testhelpers/teststorage/teststorage.go:264:10: cannot use logicalKv.Factory (value of type func(ctx "context".Context, conf *"github.com/hashicorp/vault/sdk/logical".BackendConfig) ("github.com/hashicorp/vault/sdk/logical".Backend, error)) as "github.com/lf-edge/openbao/sdk/logical".Factory value in map literal
# github.com/lf-edge/openbao/helper/builtinplugins
helper/builtinplugins/registry.go:102:26: cannot use credAliCloud.Factory (value of type func(ctx "context".Context, conf *"github.com/hashicorp/vault/sdk/logical".BackendConfig) ("github.com/hashicorp/vault/sdk/logical".Backend, error)) as "github.com/lf-edge/openbao/sdk/logical".Factory value in struct literal

... and more of the same error...
```

Looks like `logicalKv` refers to `"github.com/hashicorp/vault-plugin-secrets-kv"` which of internally refers to

```
	github.com/hashicorp/vault/api v1.9.2
	github.com/hashicorp/vault/sdk v0.10.0
```

Causing the incompatibility. Any idea how to fix this short of forking `"github.com/hashicorp/vault-plugin-secrets-kv"`?

2023-11-30 12:03 UTC, jbutlerdev commented
Good call on the replace statement. I'll give this a shot today and get back to you

2023-11-30 13:10 UTC, naphelps commented
`.../vault/api` and `.../vault/sdk` both are still currently using MPL 2.0 license still. Short-term these references should not need to be changed.

Long-term if we needed to fork some of these plugins we would need to potentially work with OpenTofu to see if they use the same plugins or not, and what org the repo would fall under.

2023-11-30 13:14 UTC, naphelps commented
Make sure all commits use `-s` or `--signoff` for sign off.

2023-12-04 11:06 UTC, Scorpil commented
@naphelps that was my original thinking as well (see `hcp_link` discussion above). However, as @jbutlerdev pointed out those modules are already forked (they're in this repo), so pointing to vault repo would be a bit dirty: first commiter who needs to modify those crucial sub-modules will be forced to solve the issue...

Besides, in this particular case it's not quite possible because the dependency is transitive: `vault-plugin-secrets-kv` improts values from hashicorp's vault, so when our codebase tries to use those - type mismatch happens.

2023-12-04 12:06 UTC, naphelps commented
Do we have a known good list of plugins that need to be additionally forked?

2023-12-04 13:25 UTC, cipherboy commented
@naphelps said:
> Do we have a known good list of plugins that need to be additionally forked?

This should be correct:

```
$ grep 'hashicorp/vault-plugin-' ./go.mod`
	github.com/hashicorp/vault-plugin-auth-alicloud v0.15.0
	github.com/hashicorp/vault-plugin-auth-azure v0.16.0
	github.com/hashicorp/vault-plugin-auth-centrify v0.15.1
	github.com/hashicorp/vault-plugin-auth-cf v0.15.0
	github.com/hashicorp/vault-plugin-auth-gcp v0.16.0
	github.com/hashicorp/vault-plugin-auth-jwt v0.16.0
	github.com/hashicorp/vault-plugin-auth-kerberos v0.10.0
	github.com/hashicorp/vault-plugin-auth-kubernetes v0.16.0
	github.com/hashicorp/vault-plugin-auth-oci v0.14.0
	github.com/hashicorp/vault-plugin-database-couchbase v0.9.2
	github.com/hashicorp/vault-plugin-database-elasticsearch v0.13.2
	github.com/hashicorp/vault-plugin-database-mongodbatlas v0.10.0
	github.com/hashicorp/vault-plugin-database-redis v0.2.1
	github.com/hashicorp/vault-plugin-database-redis-elasticache v0.2.1
	github.com/hashicorp/vault-plugin-database-snowflake v0.9.0
	github.com/hashicorp/vault-plugin-mock v0.16.1
	github.com/hashicorp/vault-plugin-secrets-ad v0.16.0
	github.com/hashicorp/vault-plugin-secrets-alicloud v0.15.0
	github.com/hashicorp/vault-plugin-secrets-azure v0.16.1
	github.com/hashicorp/vault-plugin-secrets-gcp v0.16.0
	github.com/hashicorp/vault-plugin-secrets-gcpkms v0.15.0
	github.com/hashicorp/vault-plugin-secrets-kubernetes v0.5.0
	github.com/hashicorp/vault-plugin-secrets-kv v0.15.0
	github.com/hashicorp/vault-plugin-secrets-mongodbatlas v0.10.2
	github.com/hashicorp/vault-plugin-secrets-openldap v0.11.1
	github.com/hashicorp/vault-plugin-secrets-terraform v0.7.1
```

Only one I'm not really sure about is `github.com/hashicorp/vault-plugin-mock`.

2023-12-04 13:30 UTC, Scorpil commented
Should be easy enough to comment them out for initial fork though, then take them up one-by-one. `plugin-secrets-kv` is used in many tests so it's the only one that's a must, imo.

2023-12-08 13:19 UTC, naphelps commented on .github/workflows/test-go.yml
> +          # | github.com/lf-edge/openbao/package | TestName | fips | 0 | 2 | [view results](github.com/link-to-logs) |
openbao/openbao

2023-12-08 13:19 UTC, naphelps commented on .github/scripts/report_failed_builds.sh
> +Build failed for these jobs: ${failed_jobs[*]}. Please refer to this workflow to learn more: https://github.com/lf-edge/openbao/actions/runs/$RUN_ID"
openbao/openbao

2023-12-08 13:20 UTC, naphelps commented on README.md
> +<img width="300" alt="Vault Logo" src="https://github.com/lf-edge/openbao/blob/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png">
openbao/openbao

2023-12-08 13:20 UTC, naphelps commented on README.md
> +`github.com/lf-edge/openbao/api` and `github.com/lf-edge/openbao/sdk`.
openbao/openbao

2023-12-08 13:20 UTC, naphelps commented on README.md
> +  "github.com/lf-edge/openbao/sdk/helper/testcluster/docker"
openbao/openbao

2023-12-08 13:20 UTC, naphelps commented on README.md
> +  "github.com/lf-edge/openbao/sdk/helper/testcluster/docker"
openbao/openbao

2023-12-08 13:20 UTC, naphelps commented on README.md
> +There are a variety of helpers in the `github.com/lf-edge/openbao/sdk/helper/testcluster`
openbao/openbao

2023-12-08 13:20 UTC, naphelps commented on README.md
> +ok      github.com/lf-edge/openbao/vault/external_tests/raft/raft_binary        20.960s
openbao/openbao

2023-12-08 13:20 UTC, naphelps commented on api/README.md
> +This provides the `github.com/lf-edge/openbao/api` package which contains code useful for interacting with a Vault server.
openbao/openbao

2023-12-08 13:21 UTC, naphelps commented on api/auth/approle/go.mod
> +require github.com/lf-edge/openbao/api v1.9.2
openbao/openbao

2023-12-08 13:21 UTC, naphelps commented on api/auth/approle/go.sum
> +github.com/lf-edge/openbao/api v1.9.2 h1:YjkZLJ7K3inKgMZ0wzCU9OHqc+UqMQyXsPXnf3Cl2as=
openbao/openbao

2023-12-08 13:21 UTC, naphelps commented on api/auth/approle/go.sum
> +github.com/lf-edge/openbao/api v1.9.2/go.mod h1:jo5Y/ET+hNyz+JnKDt8XLAdKs+AM0G5W0Vp1IrFI8N8=
openbao/openbao

2023-12-08 13:21 UTC, naphelps commented on api/auth/aws/go.mod
> +module github.com/lf-edge/openbao/api/auth/aws
openbao/openbao

2023-12-08 13:21 UTC, naphelps commented on api/auth/aws/go.mod
> +	github.com/lf-edge/openbao/api v1.9.2
openbao/openbao

2023-12-08 13:21 UTC, naphelps commented on api/auth/aws/go.sum
> +github.com/lf-edge/openbao/api v1.9.2 h1:YjkZLJ7K3inKgMZ0wzCU9OHqc+UqMQyXsPXnf3Cl2as=
openbao/openbao

2023-12-08 13:21 UTC, naphelps commented on api/auth/aws/go.sum
> +github.com/lf-edge/openbao/api v1.9.2/go.mod h1:jo5Y/ET+hNyz+JnKDt8XLAdKs+AM0G5W0Vp1IrFI8N8=
openbao/openbao

2023-12-08 13:21 UTC, naphelps commented on api/auth/azure/go.mod
> +module github.com/lf-edge/openbao/api/auth/azure
openbao/openbao

2023-12-08 13:21 UTC, naphelps commented on api/auth/azure/go.mod
> +require github.com/lf-edge/openbao/api v1.9.2
openbao/openbao

2023-12-08 13:21 UTC, naphelps commented on api/auth/azure/go.sum
> +github.com/lf-edge/openbao/api v1.9.2 h1:YjkZLJ7K3inKgMZ0wzCU9OHqc+UqMQyXsPXnf3Cl2as=
openbao/openbao

2023-12-08 13:21 UTC, naphelps commented on api/auth/azure/go.sum
> +github.com/lf-edge/openbao/api v1.9.2/go.mod h1:jo5Y/ET+hNyz+JnKDt8XLAdKs+AM0G5W0Vp1IrFI8N8=
openbao/openbao

2023-12-08 13:22 UTC, naphelps commented on api/auth/gcp/go.mod
> +	github.com/lf-edge/openbao/api v1.9.2
openbao/openbao

2023-12-08 13:22 UTC, naphelps commented on api/auth/gcp/go.sum
> +github.com/lf-edge/openbao/api v1.9.2 h1:YjkZLJ7K3inKgMZ0wzCU9OHqc+UqMQyXsPXnf3Cl2as=
openbao/openbao

2023-12-08 13:22 UTC, naphelps commented on api/auth/gcp/go.sum
> +github.com/lf-edge/openbao/api v1.9.2/go.mod h1:jo5Y/ET+hNyz+JnKDt8XLAdKs+AM0G5W0Vp1IrFI8N8=
openbao/openbao

2023-12-08 13:22 UTC, naphelps commented on api/auth/kubernetes/go.mod
> +module github.com/lf-edge/openbao/api/auth/kubernetes
openbao/openbao

2023-12-08 13:22 UTC, naphelps commented on api/auth/kubernetes/go.mod
> +require github.com/lf-edge/openbao/api v1.9.2
openbao/openbao

2023-12-08 13:22 UTC, naphelps commented on api/auth/kubernetes/go.sum
> +github.com/lf-edge/openbao/api v1.9.2 h1:YjkZLJ7K3inKgMZ0wzCU9OHqc+UqMQyXsPXnf3Cl2as=
openbao/openbao

2023-12-08 13:22 UTC, naphelps commented on api/auth/kubernetes/go.sum
> +github.com/lf-edge/openbao/api v1.9.2/go.mod h1:jo5Y/ET+hNyz+JnKDt8XLAdKs+AM0G5W0Vp1IrFI8N8=
openbao/openbao

2023-12-08 13:22 UTC, naphelps commented on api/auth/ldap/go.mod
> +module github.com/lf-edge/openbao/api/auth/ldap
openbao/openbao

2023-12-08 13:22 UTC, naphelps commented on api/auth/ldap/go.mod
> +require github.com/lf-edge/openbao/api v1.9.2
openbao/openbao

2023-12-08 13:23 UTC, naphelps commented on api/auth/userpass/go.mod
> +module github.com/lf-edge/openbao/api/auth/userpass
openbao/openbao

2023-12-08 13:23 UTC, naphelps commented on api/auth/userpass/go.sum
> +github.com/lf-edge/openbao/api v1.9.2 h1:YjkZLJ7K3inKgMZ0wzCU9OHqc+UqMQyXsPXnf3Cl2as=
openbao/openbao

2023-12-08 13:23 UTC, naphelps commented on api/auth/ldap/go.sum
> +github.com/lf-edge/openbao/api v1.9.2 h1:YjkZLJ7K3inKgMZ0wzCU9OHqc+UqMQyXsPXnf3Cl2as=
openbao/openbao

2023-12-08 13:23 UTC, naphelps commented on api/auth/ldap/go.sum
> +github.com/lf-edge/openbao/api v1.9.2/go.mod h1:jo5Y/ET+hNyz+JnKDt8XLAdKs+AM0G5W0Vp1IrFI8N8=
openbao/openbao

2023-12-08 13:23 UTC, naphelps commented on api/auth/userpass/go.sum
> +github.com/lf-edge/openbao/api v1.9.2/go.mod h1:jo5Y/ET+hNyz+JnKDt8XLAdKs+AM0G5W0Vp1IrFI8N8=
openbao/openbao

2023-12-08 13:24 UTC, naphelps commented on api/README.md
> +[![GoDoc](https://godoc.org/github.com/lf-edge/openbao/api?status.png)](https://godoc.org/github.com/lf-edge/openbao/api)
openbao/openbao

2023-12-08 13:25 UTC, naphelps commented on changelog/note.tmpl
> +{{.Body}}{{if not (stringHasPrefix .Issue "_")}} [[GH-{{- .Issue -}}](https://github.com/lf-edge/openbao/pull/{{- .Issue -}})]{{end}}
openbao/openbao

2023-12-08 13:26 UTC, naphelps requested changes
Missed some of the lf-edge repo renames to openbao/openbao. 43 occurrences.

2023-12-20 14:55 UTC, naphelps approved these changes

2023-12-20 14:57 UTC, merged