fix: variable name collision in docker-entrypoint
openbao/openbao pull request #446
Opened 2024-08-02 10:01 UTC by jackhodgkiss

In the `docker-entrypoint.sh` script there is an issue with collision between the variable name `BAO_CLUSTER_ADDR` which is used for the redirect interface and for local JSON configuration. Any attempt to set JSON configuration will cause `bao` to fail when attempt to parse what it expects is the cluster interface when it actually JSON configuration.

Therefore, in the lines relating to local JSON configuration the variable has been renamed to `BAO_LOCAL_CONFIG` allowing for users to provide custom JSON configuration without also breaking the cluster address.

Closes #445

2024-08-02 14:12 UTC, Alex-Welsh approved these changes

2024-08-02 19:03 UTC, JanMa commented
LGTM :heavy_check_mark: 
Thanks a lot for this fix @jackhodgkiss

2024-08-02 19:04 UTC, JanMa approved these changes

2024-08-02 20:05 UTC, JanMa commented
Hello @jackhodgkiss can you maybe GPG/SSH sign your commit so it shows up as `verified` in the UI?
We have a branch protection rule which requires this so I can't merge your PR. Please note that this requirement is currently up for discussion, see #399. It would be great to get your views on the matter as a first time committer to OpenBao.

2024-08-02 20:05 UTC, JanMa requested changes
Please GPG/SSH sign your commit

2024-08-03 16:34 UTC, jackhodgkiss commented
Hello @JanMa I have signed the commit with my GPG key.

2024-08-03 18:13 UTC, JanMa approved these changes
Thanks again for your contribution @jackhodgkiss

2024-08-03 18:13 UTC, merged