Auto-TLS listeners via ACME
openbao/openbao pull request #857
Opened 2024-12-25 23:09 UTC by cipherboy

This adds the ability to provision a TLS listener without specifying certificates; instead, [CertMagic](https://github.com/caddyserver/certmagic) (from the authors of [Caddy](https://caddyserver.com/)) will be used to provision a just-in-time certificate, received via ACME. We support HTTP-01 and TLS-ALPN-01 challenge types.

This required updating the Dockerfile so that port 80 can be optionally exposed. Notably, ACME requires solving ALPN challenges on port 443 and HTTP challenges on port 80. If directly exposing the container, it can now bind to privileged ports by using the `BAO_SKIP_DROP_ROOT`. However, if a load balancer or firewall port redirection is used, the challenges will be exposed on all ports and root permissions can be dropped.

Resolves: #17

2025-01-13 16:21 UTC, cipherboy commented
@DanGhita @JanMa This should be ready for review now!

2025-02-08 23:29 UTC, JanMa requested changes
Not completely done yet, but here are already some remarks

2025-02-08 23:29 UTC, JanMa commented on internalshared/listenerutil/tls_acme.go
> +		TestCA:                  l.TLSACMECADirectory,
I think we shouldn't set this to the same value as `CA` by default. Either leave it empty or allow the user to set this using a config variable

2025-02-08 23:29 UTC, JanMa commented on website/content/docs/configuration/listener/tcp.mdx
> +- `tls_acme_cache_path` `(string: "~/.local/share/certmagic")` - Specifies the
This default implies that the (linux) user running OpenBao has a home directory. In our Docker images and DEB/RPM packages, openbao is running as a system user without a home directory. So accessing the default path might return an error. 

Not sure what a sensible default might be though. Maybe `/var/lib/openbao/certmagic` :thinking:

2025-02-08 23:29 UTC, JanMa commented on website/content/docs/configuration/listener/tcp.mdx
> +- `tls_acme_domains` `(string: "")` - An optional but strongly recommended
This is a list of strings

2025-02-08 23:29 UTC, JanMa commented on website/content/docs/configuration/listener/tcp.mdx
> +  ignored on the OpenBao side, it is.
I think you are missing the rest of the sentence here?

2025-02-08 23:43 UTC, cipherboy commented on internalshared/listenerutil/tls_acme.go
> +type zapHclCore struct {
@JanMa The issue is there's two different formats and stdout vs file writing, so it gets hard to implement it in a 1:1 compatible way. The other thing you risk is, but not calling into hclog, that you interrupt another log line (because you don't have locking), such as:

```
{START OF HCLOG LINE}{SOME ZLOG LINE}
{END OF HCLOG LINE}
```

and so you'll get corrupted data in, say, JSON format. I think you're really better off with this hack, though I'm happy extracting it out somewhere else if you prefer (e.g. `tls_acme_zap_hclog_compat.go`).

2025-02-08 23:53 UTC, cipherboy commented on internalshared/listenerutil/tls_acme.go
> +		TestCA:                  l.TLSACMECADirectory,
It is not clear from the certmagic docs when this is used. I think it is used when `attempts > 0` perhaps? But that makes no sense.

2025-02-08 23:56 UTC, cipherboy commented on website/content/docs/configuration/listener/tcp.mdx
> +- `tls_acme_cache_path` `(string: "~/.local/share/certmagic")` - Specifies the
> This default implies that the (linux) user running OpenBao has a home directory. In our Docker images and DEB/RPM packages, openbao is running as a system user without a home directory. So accessing the default path might return an error.

Hmmm, I'm not sure how we'd be able to conditionally check if we can use any other path, tbh. This is also not our default, but certmagic's default: https://pkg.go.dev/github.com/caddyserver/certmagic#readme-storage

`/var/lib/openbao` may not exist, and so the `openbao` user may not have permissions to write to it. I think that means we'd have to fall back to `$TEMPDIR`?

2025-02-08 23:57 UTC, cipherboy commented on website/content/docs/configuration/listener/tcp.mdx
> +- `tls_acme_domains` `(string: "")` - An optional but strongly recommended
Ah, yes, good catch.

2025-02-09 00:05 UTC, cipherboy commented on internalshared/listenerutil/tls_acme.go
> +type Reloadable interface {
Thanks, fixed.

2025-02-09 00:10 UTC, cipherboy commented on internalshared/listenerutil/tls_acme.go
> +		TestCA:                  l.TLSACMECADirectory,
I set this to the empty string. I think that means we won't ever use the TestCA, which is probably ideal behavior, given you can't explicitly tell CertMagic to use the TestCA>

2025-02-09 20:06 UTC, JanMa commented on internalshared/listenerutil/tls_acme.go
> +		TestCA:                  l.TLSACMECADirectory,
By default certmagic sets this to the Let's Encrypt Staging CA
https://github.com/caddyserver/certmagic/blob/v0.21.7/acmeissuer.go#L638-L643

2025-02-09 20:18 UTC, cipherboy commented on internalshared/listenerutil/tls_acme.go
> +		TestCA:                  l.TLSACMECADirectory,
@JanMa But only if `CA == DefaultACME.CA`: 

https://github.com/caddyserver/certmagic/blob/3f666293f0e588b804d5bc4e792a841d68a3f27c/acmeissuer.go#L183-L189

Which it doesn't, so it'll be blank?

2025-02-09 20:23 UTC, JanMa commented on internalshared/listenerutil/tls_acme.go
> +		TestCA:                  l.TLSACMECADirectory,
Right, so let's set this blank by default and enable the user to override it if they want?

2025-02-09 20:25 UTC, JanMa commented on website/content/docs/configuration/listener/tcp.mdx
> +- `tls_acme_cache_path` `(string: "~/.local/share/certmagic")` - Specifies the
Interesting, the certmagic default is subtly different from what you wrote

> By default, CertMagic stores assets on the local file system in $HOME/.local/share/certmagic (and honors $XDG_DATA_HOME if set). CertMagic will create the directory if it does not exist. If writes are denied, things will not be happy, so make sure CertMagic can write to it!

I guess this is fine then

2025-02-09 20:30 UTC, cipherboy commented on internalshared/listenerutil/tls_acme.go
> +		TestCA:                  l.TLSACMECADirectory,
@JanMa Hmm... Like I said, I don't think we ever use it. There's no switch in certmagic to actually force it to use the TestCA, so I'm not sure what value it serves. I think the only case it gets used is if the main issuance fails for some reason, it'll try falling back to the test server to see if that one works, before retrying on the main server.

Mostly I think that's in the interest of avoiding rate limiting in the event of a configuration failure, though CertMagic should already respect the rate limiting (and has its own).

2025-02-09 20:38 UTC, cipherboy commented on internalshared/listenerutil/tls_acme.go
> +		TestCA:                  l.TLSACMECADirectory,
Filed as https://github.com/caddyserver/certmagic/issues/330

2025-02-09 20:48 UTC, JanMa approved these changes

2025-02-12 12:06 UTC, JanMa approved these changes

2025-02-12 13:38 UTC, merged

2025-02-12 13:38 UTC, cipherboy commented
Thanks @JanMa!